using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using MermaidDiagramExporter.Core;
using MermaidDiagramExporter.Export;

namespace MermaidDiagramExporter.Gui.Design;

/// <summary>
/// Exports a DesignGraph to various formats: Mermaid (.mmd), C# stub source,
/// and JSON (via DesignSerialization). Per docs/design/06-export-pipeline.md.
/// </summary>
public static class DesignExporter
{
    /// <summary>
    /// Exports the design to Mermaid format by converting to TypeGraph and
    /// delegating to the existing MermaidGraphExporter. This guarantees
    /// identical output between Analyze Mode and Design Mode for the same
    /// content.
    /// </summary>
    public static string ToMermaid(DesignGraph graph)
    {
        var typeGraph = ToTypeGraph(graph);
        return MermaidGraphExporter.BuildDiagram(typeGraph);
    }

    /// <summary>
    /// Exports the design to a minimal but compilable C# stub. The stub
    /// contains class/interface/struct declarations with member signatures
    /// only — no method bodies, no constructors with field init. It's a
    /// starting point, not a complete implementation.
    /// </summary>
    public static string ToCSharpStub(DesignGraph graph)
    {
        var sb = new StringBuilder();

        // Header comment
        sb.AppendLine("// Auto-generated by MermaidDiagramExporter Design Mode");
        sb.AppendLine($"// Date: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine($"// Source: {graph.Title}");
        sb.AppendLine();

        // Always include System for common types
        sb.AppendLine("using System;");
        sb.AppendLine();

        // Group classes by namespace
        var byNamespace = graph.Classes
            .GroupBy(c => c.Namespace ?? "")
            .OrderBy(g => g.Key);

        bool first = true;
        foreach (var nsGroup in byNamespace)
        {
            if (!first) sb.AppendLine();
            first = false;

            if (!string.IsNullOrEmpty(nsGroup.Key))
            {
                sb.AppendLine($"namespace {nsGroup.Key}");
                sb.AppendLine("{");
            }

            // Sort classes alphabetically within each namespace
            var sortedClasses = nsGroup.OrderBy(c => c.Name).ToList();
            foreach (var cls in sortedClasses)
            {
                AppendClass(sb, cls, graph);
            }

            if (!string.IsNullOrEmpty(nsGroup.Key))
            {
                sb.AppendLine("}");
            }
        }

        return sb.ToString();
    }

    private static void AppendClass(StringBuilder sb, DesignClass cls, DesignGraph graph)
    {
        string indent = string.IsNullOrEmpty(cls.Namespace ?? "") ? "" : "    ";

        // Determine base class and interfaces from edges
        string? baseClass = null;
        var interfaces = new List<string>();

        foreach (var edge in graph.Edges)
        {
            if (edge.FromClassId != cls.Id) continue;

            var targetClass = graph.Classes.FirstOrDefault(c => c.Id == edge.ToClassId);
            if (targetClass == null) continue;

            if (edge.Kind == EdgeKind.Inheritance)
            {
                baseClass ??= targetClass.Name;
            }
            else if (edge.Kind == EdgeKind.Implements)
            {
                interfaces.Add(targetClass.Name);
            }
        }

        // Build declaration
        string keyword = cls.Kind switch
        {
            ClassKind.Interface => "interface",
            ClassKind.Enum => "enum",
            ClassKind.Struct => "struct",
            ClassKind.StaticClass => "static class",
            ClassKind.AbstractClass => "abstract class",
            _ => "class"
        };

        string inheritance = "";
        if (baseClass != null) inheritance = $" : {baseClass}";
        else if (interfaces.Count > 0) inheritance = $" : {string.Join(", ", interfaces)}";

        sb.AppendLine($"{indent}public {keyword} {cls.Name}{inheritance}");
        sb.AppendLine($"{indent}{{");

        // Enums: members become enum values
        if (cls.Kind == ClassKind.Enum)
        {
            int i = 0;
            foreach (var member in cls.Members)
            {
                string suffix = i < cls.Members.Count - 1 ? "," : "";
                sb.AppendLine($"{indent}    {member.Name} = {i}{suffix}");
                i++;
            }
        }
        else
        {
            // Sort members: fields, properties, constructors, methods
            var sortedMembers = cls.Members
                .OrderBy(m => m.Kind)
                .ThenBy(m => m.Name)
                .ToList();

            foreach (var member in sortedMembers)
            {
                AppendMember(sb, member, cls, indent);
            }
        }

        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    private static void AppendMember(StringBuilder sb, DesignMember member, DesignClass cls, string indent)
    {
        string visPrefix = member.Visibility switch
        {
            Visibility.Public => "+",
            Visibility.Private => "-",
            Visibility.Protected => "#",
            Visibility.Internal => "~",
            _ => "+"
        };

        // For C# output, use C# visibility keywords instead of UML +/-
        string visKeyword = member.Visibility switch
        {
            Visibility.Public => "public",
            Visibility.Private => "private",
            Visibility.Protected => "protected",
            Visibility.Internal => "internal",
            _ => "public"
        };

        string staticModifier = cls.Kind == ClassKind.StaticClass ? "static " : "";
        string abstractModifier = cls.Kind == ClassKind.AbstractClass && member.Kind == MemberKind.Method ? "abstract " : "";

        switch (member.Kind)
        {
            case MemberKind.Field:
                sb.AppendLine($"{indent}    {visKeyword} {staticModifier}{member.TypeName} {member.Name};");
                break;

            case MemberKind.Property:
                sb.AppendLine($"{indent}    {visKeyword} {staticModifier}{member.TypeName} {member.Name} {{ get; set; }}");
                break;

            case MemberKind.Method:
                string paramsStr = string.Join(", ", member.Parameters.Select(p => $"{p.TypeName} {p.Name}"));
                sb.AppendLine($"{indent}    {visKeyword} {staticModifier}{abstractModifier}{member.TypeName} {member.Name}({paramsStr}) {{ }}");
                break;

            case MemberKind.Constructor:
                string ctorParams = string.Join(", ", member.Parameters.Select(p => $"{p.TypeName} {p.Name}"));
                sb.AppendLine($"{indent}    {visKeyword} {cls.Name}({ctorParams}) {{ }}");
                break;

            case MemberKind.Event:
                sb.AppendLine($"{indent}    {visKeyword} {staticModifier}event {member.TypeName} {member.Name};");
                break;
        }
    }

    /// <summary>
    /// Converts a DesignGraph to a TypeGraph so it can be consumed by the
    /// existing layout and rendering pipeline. Per docs/design/06.
    /// </summary>
    public static TypeGraph ToTypeGraph(DesignGraph design)
    {
        var nodes = design.Classes.Select(ToTypeNode).ToList();
        var edges = design.Edges.Select(ToTypeEdge).ToList();
        var groups = BuildNamespaceGroups(design);

        return new TypeGraph(
            title: design.Title,
            nodes: nodes,
            edges: edges,
            groups: groups,
            metadata: new TypeGraphMetadata
            {
                GeneratedAtUtc = DateTime.UtcNow,
                SourceKind = GraphSourceKind.Unknown, // M5: no Design-specific kind yet
                Options = new GraphBuildOptions(),
                SourceDescription = $"Design: {design.Title}"
            });
    }

    private static TypeNodeData ToTypeNode(DesignClass cls)
    {
        var stereotypes = new List<string>();
        if (!string.IsNullOrEmpty(cls.Stereotype))
            stereotypes.Add(cls.Stereotype);

        return new TypeNodeData
        {
            Id = cls.Id,
            DisplayName = cls.Name,
            Namespace = cls.Namespace ?? "",
            Kind = ToTypeNodeKind(cls.Kind),
            Members = cls.Members.Select(ToTypeMember).ToList(),
            Stereotypes = stereotypes
        };
    }

    private static TypeEdgeData ToTypeEdge(DesignEdge edge)
    {
        return new TypeEdgeData
        {
            FromNodeId = edge.FromClassId,
            ToNodeId = edge.ToClassId,
            Kind = ToTypeEdgeKind(edge.Kind),
            Label = edge.Label ?? ""
        };
    }

    private static TypeNodeKind ToTypeNodeKind(ClassKind kind) => kind switch
    {
        ClassKind.Interface => TypeNodeKind.Interface,
        ClassKind.Enum => TypeNodeKind.Enum,
        ClassKind.Struct => TypeNodeKind.Struct,
        ClassKind.StaticClass => TypeNodeKind.StaticClass,
        ClassKind.AbstractClass => TypeNodeKind.AbstractClass,
        _ => TypeNodeKind.Class
    };

    /// <summary>
    /// Maps DesignEdgeKind to TypeEdgeKind. The three "extra" design kinds
    /// (Dependency, Aggregation, Composition) collapse to Association,
    /// per docs/design/06. This is a lossy conversion — the validator
    /// warns users about it.
    /// </summary>
    private static TypeEdgeKind ToTypeEdgeKind(EdgeKind kind) => kind switch
    {
        EdgeKind.Inheritance => TypeEdgeKind.Inheritance,
        EdgeKind.Implements => TypeEdgeKind.Implements,
        EdgeKind.Association => TypeEdgeKind.Association,
        EdgeKind.Dependency => TypeEdgeKind.Association,
        EdgeKind.Aggregation => TypeEdgeKind.Association,
        EdgeKind.Composition => TypeEdgeKind.Association,
        _ => TypeEdgeKind.Association
    };

    private static TypeMemberData ToTypeMember(DesignMember member)
    {
        return new TypeMemberData
        {
            Name = member.Name,
            TypeName = member.TypeName,
            Kind = ToTypeMemberKind(member.Kind),
            Visibility = ToTypeVisibility(member.Visibility)
        };
    }

    private static TypeMemberKind ToTypeMemberKind(MemberKind kind) => kind switch
    {
        MemberKind.Field => TypeMemberKind.Field,
        MemberKind.Property => TypeMemberKind.Property,
        MemberKind.Method => TypeMemberKind.Method,
        // Constructor and Event collapse to Method in TypeMemberKind (which only
        // has Field/Property/Method). The original distinction is lost in
        // the TypeGraph export — the C# stub export keeps all distinctions.
        MemberKind.Constructor => TypeMemberKind.Method,
        MemberKind.Event => TypeMemberKind.Method,
        _ => TypeMemberKind.Field
    };

    private static TypeVisibility ToTypeVisibility(Visibility v) => v switch
    {
        Visibility.Public => TypeVisibility.Public,
        Visibility.Private => TypeVisibility.Private,
        Visibility.Protected => TypeVisibility.Protected,
        Visibility.Internal => TypeVisibility.Internal,
        _ => TypeVisibility.Public
    };

    private static List<TypeGroupData> BuildNamespaceGroups(DesignGraph design)
    {
        var groups = new List<TypeGroupData>();
        var byNamespace = design.Classes
            .GroupBy(c => c.Namespace ?? "")
            .Where(g => !string.IsNullOrEmpty(g.Key));

        foreach (var nsGroup in byNamespace)
        {
            groups.Add(new TypeGroupData
            {
                Id = $"Namespace:{nsGroup.Key}",
                Label = nsGroup.Key,
                Kind = TypeGroupKind.Namespace,
                NodeIds = nsGroup.Select(c => c.Id).ToArray()
            });
        }

        return groups;
    }

    // ── Reverse conversion: TypeGraph → DesignGraph ──

    /// <summary>
    /// Converts a scanned <see cref="TypeGraph"/> into an editable
    /// <see cref="DesignGraph"/>, preserving IDs, names, namespaces, kinds,
    /// members, and edges. Layout positions are auto-arranged in a grid.
    /// Used by the "Edit in Design" button in Analyze Mode.
    /// </summary>
    public static DesignGraph FromTypeGraph(TypeGraph typeGraph, List<GraphNode>? layoutNodes = null)
    {
        var nodeMap = layoutNodes?.ToDictionary(n => n.Id) ?? new Dictionary<string, GraphNode>();

        var design = new DesignGraph
        {
            Title = typeGraph.Title,
            Classes = typeGraph.Nodes.Select(n =>
            {
                var cls = new DesignClass
                {
                    Id = n.Id,
                    Name = n.DisplayName,
                    Namespace = n.Namespace,
                    Kind = FromTypeNodeKind(n.Kind),
                    Stereotype = n.Stereotypes.FirstOrDefault(),
                    Members = n.Members.Select(FromTypeMember).ToList()
                };

                // Use layout positions if available, otherwise auto-arrange
                if (nodeMap.TryGetValue(n.Id, out var layoutNode))
                {
                    cls.X = layoutNode.X;
                    cls.Y = layoutNode.Y;
                    cls.Width = layoutNode.Width;
                    cls.Height = layoutNode.Height;
                }

                return cls;
            }).ToList(),

            Edges = typeGraph.Edges.Select(e => new DesignEdge
            {
                FromClassId = e.FromNodeId,
                ToClassId = e.ToNodeId,
                Kind = FromTypeEdgeKind(e.Kind),
                Label = e.Label
            }).ToList(),

            Namespaces = typeGraph.Groups
                .Where(g => g.Kind == TypeGroupKind.Namespace)
                .Select(g => new DesignNamespace
                {
                    Id = g.Id,
                    Name = g.Label
                }).ToList()
        };

        // Auto-arrange classes that don't have layout positions
        AutoArrangeUnpositioned(design);

        return design;
    }

    private static ClassKind FromTypeNodeKind(TypeNodeKind kind) => kind switch
    {
        TypeNodeKind.Interface => ClassKind.Interface,
        TypeNodeKind.Enum => ClassKind.Enum,
        TypeNodeKind.Struct => ClassKind.Struct,
        TypeNodeKind.StaticClass => ClassKind.StaticClass,
        TypeNodeKind.AbstractClass => ClassKind.AbstractClass,
        _ => ClassKind.Class
    };

    private static EdgeKind FromTypeEdgeKind(TypeEdgeKind kind) => kind switch
    {
        TypeEdgeKind.Inheritance => EdgeKind.Inheritance,
        TypeEdgeKind.Implements => EdgeKind.Implements,
        _ => EdgeKind.Association
    };

    private static DesignMember FromTypeMember(TypeMemberData m)
    {
        return new DesignMember
        {
            Name = m.Name,
            TypeName = m.TypeName,
            Kind = m.Kind switch
            {
                TypeMemberKind.Property => MemberKind.Property,
                TypeMemberKind.Method => MemberKind.Method,
                _ => MemberKind.Field
            },
            Visibility = m.Visibility switch
            {
                TypeVisibility.Private => Visibility.Private,
                TypeVisibility.Protected => Visibility.Protected,
                TypeVisibility.Internal => Visibility.Internal,
                _ => Visibility.Public
            },
            Parameters = m.Parameters.Select(p => new DesignParameter
            {
                Name = p.Name,
                TypeName = p.TypeName
            }).ToList()
        };
    }

    /// <summary>
    /// Places classes that have X=Y=0 (no layout data) into a grid.
    /// Preserves positions from classes that already have them.
    /// </summary>
    private static void AutoArrangeUnpositioned(DesignGraph design)
    {
        const float cellW = 260f;
        const float cellH = 160f;
        const int cols = 4;

        var unpositioned = design.Classes.Where(c => c.X == 0 && c.Y == 0).ToList();
        if (unpositioned.Count == 0) return;

        // Find the bottom-right of existing positioned classes
        float startX = 0, startY = 0;
        var positioned = design.Classes.Where(c => c.X != 0 || c.Y != 0).ToList();
        if (positioned.Count > 0)
        {
            startX = positioned.Max(c => c.X + c.Width) + 40f;
            startY = positioned.Min(c => c.Y); // align to top
        }

        int i = 0;
        foreach (var cls in unpositioned)
        {
            int col = i % cols;
            int row = i / cols;
            cls.X = startX + col * cellW;
            cls.Y = startY + row * cellH;
            i++;
        }
    }
}
